### ISSUE TITLE
Invalid argument supplied for foreach() in PatternLabListener.php on line 47

### ISSUE THREAD

**Issue by aleksip** [pattern-lab/plugin-php-data-inheritance#1]
It looks like `$patternData["lineages"]` is `false` in some cases (happened to me with some pseudo patterns), and `count(false)` returns `1`. So the `if` conditions on line 43 should probably be amended accordingly.

**Comment by dmolsen** [comment]
Have a blind fix for this in `dev`. If you could give me a use case I can replicate I'll dig into it more. I'll close once `v1.0.1` goes out.

**Comment by aleksip** [comment]
I have now created a [StarterKit](https://github.com/aleksip/starterkit-twig-include-data-tests) that should demonstrate the bug. The fix in dev seems to work.

The StarterKit is also helpful in demonstrating other bugs, for example [patternlab-php-core#16](https://github.com/pattern-lab/patternlab-php-core/issues/16) and #2. Also, if you look at Pattern Partial Nodatafile there seems to be something odd going on with Data Inheritance Plugin...

**Comment by dmolsen** [comment]
Appreciate you putting that together. So I should be able to get by with `dev` of Core, DIP, and your StarterKit to demonstrate the issues? I really need to work on my naming skills so I don't end up with really dumb acronyms >.<

Tangent but I'm going to build an acid test StarterKit to hopefully catch these issues earlier on in the future. Or at least it'll demonstrate expected input/output. For example, Issue 16 may require an rethink of how I tackle data overall.

**Comment by aleksip** [comment]
> So I should be able to get by with dev of Core, DIP, and your StarterKit to demonstrate the issues?

I tested with the `master` branch of Standard Edition for Twig, the released version of DIP :) and the StarterKit. Also with DIP `dev-dev`.

Acid Test StarterKit sounds cool!

**Comment by dmolsen** [comment]
Well, I'm finding bugs with `styleguidekit-assets-default` so I guess that's good ;)

pattern-lab/styleguidekit-assets-default#34
pattern-lab/styleguidekit-assets-default#35

**Comment by dmolsen** [comment]
Really dumb question. How do I add paths to a fairly vanilla set-up? e.g. so `@atoms` is properly parsed?

**Comment by aleksip** [comment]
Hmm, not sure if this is what you mean but there has been automatic support for top-level folders since [Twig PatternEngine 0.7.2](https://github.com/pattern-lab/patternengine-php-twig/releases/tag/v0.7.2). A plugin is needed for anything else I think.

Didn't the test StarterKit Twig namespace includes work with your setup?

**Comment by dmolsen** [comment]
Not looking like it. I chalk up my forgetting that feature to the fact that I track a lot across PL ;) I'll double-check and see what I could have f'ed up.

**Comment by dmolsen** [comment]
@aleksip -

_facepalm_

Namespaces are working. Titles are the include tags wrapped in `{% raw %}` tags. Ignore me. Long week.

**Comment by nstriedinger** [comment]
I'm not sure if this is the correct place to post this question, but I'm also running into this issue. In Patternlab all my includes have been changed to twig template namespaces and now there is no lineage link `The <strong>{{ patternName }}</strong> pattern contains the following patterns:`

**Comment by therealpecus** [comment]
bump for interest. currently hitting this bug with basic inheritance

**Comment by aleksip** [comment]
@nstriedinger @therealpecus You might want to try [Data Transform Plugin](https://github.com/aleksip/plugin-data-transform). It has a slightly different implementation of data inheritance, but it might suit your needs. Using the other features of DTP is completely optional. The latest versions work with Twig PatternEngine only, but [v0.10.2](https://github.com/aleksip/plugin-data-transform/releases/tag/v0.10.2) should work with Mustache PatternEngine as well.

**Comment by therealpecus** [comment]
Thanks @aleksip , I'll give it a try!

**Comment by RedLucas** [comment]
Hey, I run into the exact same problem. Data transform doesn't really do what I want... This bug's been here for over a year eh? Does anyone know off-hand how big an issue this is? Like is it just a matter to type checking or does a bunch of this have to be rewritten? I could look at it too, I just... I don't really want to duplicate work here..

**Comment by aleksip** [comment]
@nstriedinger @therealpecus @RedLucas I believe everything should now work using Twig PatternEngine v2.1.3. Can you confirm this?

**Comment by tanc** [comment]
@aleksip I can confirm that using https://github.com/aleksip/plugin-data-transform works now with the latest Twig PatternEngine.

I've also tested this plugin but inheritance seems to only half work. I'm still seeing a couple of `Invalid argument supplied for foreach()` while other included patterns are loaded with their lineage data intact. I'm not going to test this plugin any further as the plugin-data-transform works well so I'll stick with that.

I'm very happy to have working lineage as it greatly simplifies Pattern Lab data management. Thanks for everyone's hard work on this!

**Comment by aleksip** [comment]
@tanc Thanks, good to know!
